debug: false
server:
  port: ${SERVER_PORT:8094}
  context-path: /bluepay-service
spring:
  profiles:
    active: prod
  application:
    name: bluepay-service
  redis:
    host: 127.0.0.1
    port: 6379


http:
  maxTotal: 200
  defaultMaxPerRoute: 100
  connectTimeout: 1000
  connectionRequestTimeout: 30000
  socketTimeout: 30000
  staleConnectionCheckEnabled: true

redisson:
  address: redis://127.0.0.1:6379
  password:
  #master-name: mymaster
  #sentinel-addresses: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381

thirdparty:
  bluepay:
    productId:
    productIdKey:
    operatorId:


app:
  config:
    bizSystem: panda
    bizService: payserve
    log:
       path: ${PWD}
       level: info
