environment: product

server:
  port: ${SERVER_PORT:8094}

spring:
  redis:
      host: 127.0.0.1
      port: 6379

default:
  primary:
     datasource:
        url: jdbc:postgresql://127.0.0.1:5236/bluepay_prodction?tcpKeepAlive=true&autoReconnect=true&PGTZ=7
        username: main_user
        password:
        driverClassName: org.postgresql.Driver
        #初始化连接数
        initialSize: 5
        #最多空闲连接数
        maxIdle: 5
        #最大链接数
        maxActive: 60
        #配置获取连接等待超时的时间,单位毫秒
        maxWait: 60000
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        #校验sql
        validationQuery: SELECT 1
        #获取链接时，验证连接可用性
        testOnBorrow: true

redisson:
  address: redis://127.0.0.1:6379
  password:
  #master-name: mymaster
  #sentinel-addresses: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381

thirdparty:
  bluepay:
    productId:
    productIdKey:
    operatorId:


app:
  config:
    log:
       path: /srv/logs/bluepay
       level: INFO

url:
  bluepay:
    #收款
    gatherUrl: http://in.webpay.bluepay.tech/bluepay/offline.php
    #放款
    fintechUrl: http://in.api.bluepay.tech/charge/indonesiaFintechTransfer/transferBalance
    #查询
    fintechQueryUrl: http://chargequeryid.bluepay.tech/charge/indonesiaFintechTransfer/queryTransfer
    #查询
    gatherQueryUrl: http://chargequeryid.bluepay.tech/charge/service/queryTransDetail